spring:
  jpa:
    database: mysql
    show-sql: true
    format-sql: true
    hibernate.ddl-auto: validate
    
  datasource:
    url: jdbc:mysql://docker/movie_app
    username: vitek
    password: Password1
    driver-class-name: com.mysql.jdbc.Driver
